const allCharms = [
  {
    id: 1,
    name: "Star",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/1_Star.JPEG",
  },
  {
    id: 2,
    name: "Moon",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/2_Moon.JPEG",
  },
  {
    id: 3,
    name: "Compass",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/3_Compass.JPEG",
  },
  {
    id: 4,
    name: "Key",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/4_Key.JPEG",
  },
  {
    id: 5,
    name: "Bow",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/5_Cupid_Bow.JPEG",
  },
  {
    id: 6,
    name: "Arrow",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/6_Arrow.JPEG",
  },
  {
    id: 7,
    name: "Thunder",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/7_Thunder.JPEG",
  },
  {
    id: 8,
    name: "Anchor",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/8_Anchor.JPEG",
  },
  {
    id: 9,
    name: "Shell",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/9_Shell.JPEG",
  },
  {
    id: 10,
    name: "Cherry",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/10_Cherry.JPEG",
  },
  {
    id: 11,
    name: "Cupcake",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/11_Cupcake.JPEG",
  },
  {
    id: 12,
    name: "Crown",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/12_Crown.JPEG",
  },
  {
    id: 13,
    name: "Teddy Bear",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/13_Teddy.JPEG",
  },
  {
    id: 14,
    name: "Evil Eye",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/14_Evil_eye.JPEG",
  },
  {
    id: 15,
    name: "Hamsa",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/15_Hamsa.JPEG",
  },
  {
    id: 16,
    name: "Love",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/16_Love.JPEG",
  },
  {
    id: 17,
    name: "Music",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/17_Music.JPEG",
  },
  {
    id: 18,
    name: "Clover",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/18_Clover.JPEG",
  },
  {
    id: 19,
    name: "Cross",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/19_Cross.JPEG",
  },
  {
    id: 20,
    name: "Plane",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/20_Plane.JPEG",
  },
  {
    id: 21,
    name: "Palm Tree",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/21_Palm_Tree.JPEG",
  },
  {
    id: 22,
    name: "Snow",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/22_Snowflake.JPEG",
  },
  {
    id: 23,
    name: "Hot Air Balloon",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/23_Hot_Air_Balloon.JPEG",
  },
  {
    id: 24,
    name: "Leaf",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/24_Leaf.JPEG",
  },
  {
    id: 25,
    name: "Puzzle",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/25_Puzzle.JPEG",
  },
  {
    id: 26,
    name: "Infinity",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/26_Infinity.JPEG",
  },
  {
    id: 27,
    name: "Cocktail",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/27_Cocktail.JPEG",
  },
  {
    id: 28,
    name: "Pineapple",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/28_Pineapple.JPEG",
  },
  {
    id: 29,
    name: "Solid Heart",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/29_Solid_Heart.JPEG",
  },
  {
    id: 30,
    name: "Heart",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/30_Heart.JPEG",
  },
  {
    id: 31,
    name: "Paw",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/31_Paw.JPEG",
  },
  {
    id: 32,
    name: "Cat",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/32_Kitty.JPEG",
  },
  {
    id: 33,
    name: "Bird",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/33_Bird.JPEG",
  },
  {
    id: 34,
    name: "Starfish",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/34_Starfish.JPEG",
  },
  {
    id: 35,
    name: "Dolphin",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/35_Dolphin.JPEG",
  },
  {
    id: 36,
    name: "Draonfly",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/36_Dragonfly.JPEG",
  },
  {
    id: 37,
    name: "Elephant",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/37_Elephant.JPEG",
  },
  {
    id: 38,
    name: "Bee",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/38_Bee.JPEG",
  },
  {
    id: 39,
    name: "Flamingo",
    type: "symbol",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/39_Flamingo.JPEG",
  },
  {
    id: 40,
    name: "Globe",
    type: "symbol",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/40_Globe.JPEG",
  },
  {
    id: 41,
    name: "Capricorn",
    type: "zodiac",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/41_Capricorn.JPEG",
  },
  {
    id: 42,
    name: "Aquarius",
    type: "zodiac",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/42_Aquarius.JPEG",
  },
  {
    id: 43,
    name: "Pisces",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/43_Pisces.JPEG",
  },
  {
    id: 44,
    name: "Aries",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/44_Aries.JPEG",
  },
  {
    id: 45,
    name: "Taurus",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/45_Taurus.JPEG",
  },
  {
    id: 46,
    name: "Gemini",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/46_Gemini.JPEG",
  },
  {
    id: 47,
    name: "Cancer",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/47_Cancer.JPEG",
  },
  {
    id: 48,
    name: "Leo",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/48_Leo.JPEG",
  },
  {
    id: 49,
    name: "Virgo",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/49_Virgo.JPEG",
  },
  {
    id: 50,
    name: "Libra",
    type: "zodiac",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/50_Libra.JPEG",
  },
  {
    id: 51,
    name: "Scorpio",
    type: "zodiac",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/51_Scorpio.JPEG",
  },
  {
    id: 52,
    name: "Sagittarius",
    type: "zodiac",
    image:
      "https://drijewels-image.s3.ap-south-1.amazonaws.com/52_Sagittarius.JPEG",
  },
  {
    id: 53,
    name: "Metal - A",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/53.jpeg",
  },
  {
    id: 54,
    name: "Metal - B",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/54.jpeg",
  },
  {
    id: 55,
    name: "Metal - C",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/55.jpeg",
  },
  {
    id: 56,
    name: "Metal - D",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/56.jpeg",
  },
  {
    id: 57,
    name: "Metal - E",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/57.jpeg",
  },
  {
    id: 58,
    name: "Metal - F",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/58.jpeg",
  },
  {
    id: 59,
    name: "Metal - G",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/59.jpeg",
  },
  {
    id: 60,
    name: "Metal - H",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/60.jpeg",
  },
  {
    id: 61,
    name: "Metal - I",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/61.jpeg",
  },
  {
    id: 62,
    name: "Metal - J",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/62.jpeg",
  },
  {
    id: 63,
    name: "Metal - K",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/63.jpeg",
  },
  {
    id: 64,
    name: "Metal - L",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/64.jpeg",
  },
  {
    id: 65,
    name: "Metal - M",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/65.jpeg",
  },
  {
    id: 66,
    name: "Metal - N",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/66.jpeg",
  },
  {
    id: 67,
    name: "Metal - O",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/67.jpeg",
  },
  {
    id: 68,
    name: "Metal - P",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/68.jpeg",
  },
  {
    id: 69,
    name: "Metal - Q",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/69.jpeg",
  },
  {
    id: 70,
    name: "Metal - R",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/70.jpeg",
  },
  {
    id: 71,
    name: "Metal - S",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/71.jpeg",
  },
  {
    id: 72,
    name: "Metal - T",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/72.jpeg",
  },
  {
    id: 73,
    name: "Metal - U",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/73.jpeg",
  },
  {
    id: 74,
    name: "Metal - V",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/74.jpeg",
  },
  {
    id: 75,
    name: "Metal - W",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/75.jpeg",
  },
  {
    id: 76,
    name: "Metal - X",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/76.jpeg",
  },
  {
    id: 77,
    name: "Metal - Y",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/77.jpeg",
  },
  {
    id: 78,
    name: "Metal - Z",
    type: "metalAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/78.jpeg",
  },
  {
    id: 79,
    name: "Diamond - A",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/79.jpeg",
  },
  {
    id: 80,
    name: "Diamond - B",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/80.jpeg",
  },
  {
    id: 81,
    name: "Diamond - C",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/81.jpeg",
  },
  {
    id: 82,
    name: "Diamond - D",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/82.jpeg",
  },
  {
    id: 83,
    name: "Diamond - E",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/83.jpeg",
  },
  {
    id: 84,
    name: "Diamond - F",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/84.jpeg",
  },
  {
    id: 85,
    name: "Diamond - G",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/85.jpeg",
  },
  {
    id: 86,
    name: "Diamond - H",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/86.jpeg",
  },
  {
    id: 87,
    name: "Diamond - I",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/87.jpeg",
  },
  {
    id: 88,
    name: "Diamond - J",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/88.jpeg",
  },
  {
    id: 89,
    name: "Diamond - K",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/89.jpeg",
  },
  {
    id: 90,
    name: "Diamond - L",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/90.jpeg",
  },
  {
    id: 91,
    name: "Diamond - M",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/91.jpeg",
  },
  {
    id: 92,
    name: "Diamond - N",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/92.jpeg",
  },
  {
    id: 93,
    name: "Diamond - O",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/93.jpeg",
  },
  {
    id: 94,
    name: "Diamond - P",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/94.jpeg",
  },
  {
    id: 95,
    name: "Diamond - Q",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/95.jpeg",
  },
  {
    id: 96,
    name: "Diamond - R",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/96.jpeg",
  },
  {
    id: 97,
    name: "Diamond - S",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/97.jpeg",
  },
  {
    id: 98,
    name: "Diamond - T",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/98.jpeg",
  },
  {
    id: 99,
    name: "Diamond - U",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/99.jpeg",
  },
  {
    id: 100,
    name: "Diamond - V",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/100.jpeg",
  },
  {
    id: 101,
    name: "Diamond - W",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/101.jpeg",
  },
  {
    id: 102,
    name: "Diamond - X",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/102.jpeg",
  },
  {
    id: 103,
    name: "Diamond - Y",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/103.jpeg",
  },
  {
    id: 104,
    name: "Diamond - Z",
    type: "diamondAlphabets",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/104.jpeg",
  },
  {
    id: 105,
    name: "Metal - 0",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/105.JPEG",
  },
  {
    id: 106,
    name: "Metal - 1",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/106.JPEG",
  },
  {
    id: 107,
    name: "Metal - 2",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/107.JPEG",
  },
  {
    id: 108,
    name: "Metal - 3",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/108.JPEG",
  },
  {
    id: 109,
    name: "Metal - 4",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/109.JPEG",
  },
  {
    id: 110,
    name: "Metal - 5",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/110.JPEG",
  },
  {
    id: 111,
    name: "Metal - 6",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/111.JPEG",
  },
  {
    id: 112,
    name: "Metal - 7",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/112.JPEG",
  },
  {
    id: 113,
    name: "Metal - 8",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/113.JPEG",
  },
  {
    id: 114,
    name: "Metal - 9",
    type: "metalNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/114.JPEG",
  },
  {
    id: 115,
    name: "Diamond - 0",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/115.JPEG",
  },
  {
    id: 116,
    name: "Diamond - 1",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/116.JPEG",
  },
  {
    id: 117,
    name: "Diamond - 2",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/117.JPEG",
  },
  {
    id: 118,
    name: "Diamond - 3",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/118.JPEG",
  },
  {
    id: 119,
    name: "Diamond - 4",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/119.JPEG",
  },
  {
    id: 120,
    name: "Diamond - 5",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/120.JPEG",
  },
  {
    id: 121,
    name: "Diamond - 6",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/121.JPEG",
  },
  {
    id: 122,
    name: "Diamond - 7",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/122.JPEG",
  },
  {
    id: 123,
    name: "Diamond - 8",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/123.JPEG",
  },
  {
    id: 124,
    name: "Diamond - 9",
    type: "diamondNumbers",
    image: "https://drijewels-image.s3.ap-south-1.amazonaws.com/124.JPEG",
  },
];

export default allCharms;
