/* eslint-disable no-useless-escape */
/* eslint-disable array-callback-return */
/* eslint-disable no-param-reassign */
const products = [
 {
  "name": "Classic Plain Band",
  "price": 3000,
  "width": "5.5mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/1_ClassicPlainBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/1_ClassicPlainBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/1_ClassicPlainBand_2.webp",
  "tags": "simple bands,bands,mens band"
 },
 {
  "name": "Solitaire Diamond Mens Band",
  "price": 4000,
  "width": "2.5mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/2_SolitaireDiamondMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/2_SolitaireDiamondMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/2_SolitaireDiamondMensBand_2.webp",
  "tags": "mensband,mens ring"
 },
 {
  "name": "Diamond Mens Band",
  "price": 4000,
  "width": "7.4mm",
  "weight": "4.45gm",
  "color": "Yellow",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/3_DiamondMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/3_DiamondMensBand_1.webp",
  "tags": "mens ring"
 },
 {
  "name": "Simple Wave Mens Band",
  "price": 4000,
  "width": "6mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/4_SimpleWaveMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/4_SimpleWaveMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/4_SimpleWaveMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/4_SimpleWaveMensBand_3.webp",
  "tags": "mens band,mens ring,bands,simple bands"
 },
 {
  "name": "Two Tone Mens Band",
  "price": 4500,
  "width": "7.9mm",
  "weight": "5.5gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/5_TwoToneMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/5_TwoToneMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/5_TwoToneMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/5_TwoToneMensBand_3.webp",
  "tags": "mens band,mens ring,bands,rose gold bands,mens"
 },
 {
  "name": "Simple Flat Diamond Band ",
  "price": 3500,
  "width": "6.8mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/6_SimpleFlatDiamondBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/6_SimpleFlatDiamondBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/6_SimpleFlatDiamondBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/6_SimpleFlatDiamondBand_3.webp",
  "tags": "mens band,mens ring"
 },
 {
  "name": "Solitaire Diamond Mens Band",
  "price": 3000,
  "width": "4mm",
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/7_SolitaireDiamondMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/7_SolitaireDiamondMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/7_SolitaireDiamondMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/7_SolitaireDiamondMensBand_3.webp",
  "tags": "mens band,mens ring,bands"
 },
 {
  "name": "Three Tone Mens Band",
  "price": 4000,
  "width": "6.5mm",
  "weight": "4.42gm",
  "color": "Three Tone",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/8_ThreeToneMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/8_ThreeToneMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/8_ThreeToneMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/8_ThreeToneMensBand_3.webp",
  "tags": "mens band ,mens ring "
 },
 {
  "name": "Plain Solitaire Mens Band ",
  "price": 4500,
  "width": "7mm",
  "weight": "4.5gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/9_PlainSolitaireMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/9_PlainSolitaireMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/9_PlainSolitaireMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/9_PlainSolitaireMensBand_3.webp",
  "tags": "mens band,mens ring,bands"
 },
 {
  "name": "Love Watch Charm",
  "price": 1999,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/10_LoveWatchCharm.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/10_LoveWatchCharm_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/10_LoveWatchCharm_2.webp",
  "length": "2.5inch",
  "tags": "watch charms,watch accessories,watch jewellery"
 },
 {
  "name": "Solitaire Heart Ring ",
  "price": 2500,
  "width": "12mm",
  "weight": "2.8gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/11_SolitaireHeartRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/11_SolitaireHeartRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/11_SolitaireHeartRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/11_SolitaireHeartRing_3.webp",
  "tags": "heart ring,solitaire ring"
 },
 {
  "name": "Baguette Band ",
  "price": 3000,
  "width": "4.5mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/12_BaguetteBand.webp",
  "tags": "bands,womens band,diamond bands"
 },
 {
  "name": "Trio Pear Ring ",
  "price": 3000,
  "width": "13mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/13_TrioPearRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/13_TrioPearRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/13_TrioPearRing_2.webp",
  "tags": "solitaire rings,pear rings,pear shape"
 },
 {
  "name": "Halo Baguette Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/14_HaloBaguetteNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/14_HaloBaguetteNecklace_1.webp https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/14_HaloBaguetteNecklace_2.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "minimal necklace,9 to 5 work wear,office wear,dainty necklace"
 },
 {
  "name": "Double Cross Band",
  "price": 2300,
  "width": "4mm",
  "weight": "2.75gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/15_DoubleCrossBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/15_DoubleCrossBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/15_DoubleCrossBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/15_DoubleCrossBand_3.webp",
  "tags": "bands"
 },
 {
  "name": "Classic Solitaire Ring ",
  "price": 2300,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/16_ClassicSolitaireRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/16_ClassicSolitaireRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/16_ClassicSolitaireRing_2.webp",
  "tags": "solitaire rings,simple rings,best seller"
 },
 {
  "name": "Name Necklace ",
  "price": 2500,
  "width": "6mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/17_NameNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "name necklace,custom orders"
 },
 {
  "name": "Radiant Diamond Hoops ",
  "price": 3500,
  "width": "30mm",
  "weight": "5gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/18_RadiantDiamondHoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/18_RadiantDiamondHoops_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/18_RadiantDiamondHoops_2.webp",
  "tags": "hoops,diamond hoops"
 },
 {
  "name": "Diamond Necklace",
  "price": 3000,
  "width": "25mm",
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/19_DiamondNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "diamond necklace"
 },
 {
  "name": "Parallel Diamond Bali ",
  "price": 2500,
  "width": "15mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/20_ParallelDiamondBali.webp"
 },
 {
  "name": "Trio Solitaire ",
  "price": 2850,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/21_TrioSolitaire.webp"
 },
 {
  "name": "Audrey Band ",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/22_AudreyBand.webp"
 },
 {
  "name": "Chain Band",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/23_ChainBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/23_ChainBand_1.webp"
 },
 {
  "name": "Double Layered Drop Necklace",
  "price": 2850,
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/24_DoubleLayeredDropNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/24_DoubleLayeredDropNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Drop Layered Necklace",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/25_DropLayeredNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/25_DropLayeredNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Evil Eye Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/26_EvilEyeNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/26_EvilEyeNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Flora Diamond Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/27_FloraDiamondNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/27_FloraDiamondNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Halo Necklace",
  "price": 2000,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/28_HaloNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/28_HaloNecklace_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/28_HaloNecklace_2.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Diamond Necklace",
  "price": 2500,
  "width": "25mm",
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/29_DiamondNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/29_DiamondNecklace_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/29_DiamondNecklace_2.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Watch Band ",
  "price": 1400,
  "width": "3mm",
  "weight": "1.5gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/30_WatchBand.webp"
 },
 {
  "name": "Watch Charm Evil Eye ",
  "price": 1650,
  "weight": "2gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/31_WatchCharmEvilEye.webp"
 },
 {
  "name": "Halo Charm Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/32_HaloCharmNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/32_HaloCharmNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Halo Minimal Studs",
  "price": 1800,
  "width": "6mm",
  "weight": "1.5gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/33_HaloMinimalStuds.webp"
 },
 {
  "name": "Oval Solitaire Band",
  "price": 3600,
  "width": "16mm",
  "weight": "5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/34_OvalSolitaireBand.webp"
 },
 {
  "name": "Initial With Evil Eye Necklace",
  "price": 2200,
  "width": "9.10mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/35_InitialWithEvilEyeNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/35_InitialWithEvilEyeNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Minimal Bezel Necklace",
  "price": 1499,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/36_MinimalBezelNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Floral Necklace",
  "price": 2500,
  "width": "25.5mm",
  "weight": "3.67gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/37_FloralNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Lilac Ring ",
  "price": 2300,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/38_LilacRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/38_LilacRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/38_LilacRing_2.webp"
 },
 {
  "name": "Chain Band",
  "price": 3000,
  "width": "7.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/39_ChainBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/39_ChainBand_1.webp"
 },
 {
  "name": "Three Tone Band",
  "price": 3500,
  "width": "13.8mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/40_ThreeToneBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/40_ThreeToneBand_1.webp"
 },
 {
  "name": "Mens Plain Band",
  "price": 2500,
  "width": "9.10mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/41_MensPlainBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/41_MensPlainBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/41_MensPlainBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/41_MensPlainBand_3.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/41_MensPlainBand_4.webp"
 },
 {
  "name": "Simple Diamond Mens Band",
  "price": 3500,
  "width": "5mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/42_SimpleDiamondMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/42_SimpleDiamondMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/42_SimpleDiamondMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/42_SimpleDiamondMensBand_3.webp"
 },
 {
  "name": "Solitaire Mens Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/43_SolitaireMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/43_SolitaireMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/43_SolitaireMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/43_SolitaireMensBand_3.webp"
 },
 {
  "name": "Mens Diamond Band",
  "price": 3500,
  "width": "7mm",
  "weight": "4.8gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/44_MensDiamondBand.webp"
 },
 {
  "name": "Simple Diamond Band",
  "price": 2500,
  "width": "6mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/45_SimpleDiamondBand.webp"
 },
 {
  "name": "Two Tone Mens Diamond Ring",
  "price": 5000,
  "width": "12mm",
  "weight": "5.5gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/46_TwoToneMensDiamondRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/46_TwoToneMensDiamondRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/46_TwoToneMensDiamondRing_2.webp"
 },
 {
  "name": "Solitaire Mens Ring",
  "price": 4500,
  "width": "10mm",
  "weight": "5gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/47_SolitaireMensRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/47_SolitaireMensRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/47_SolitaireMensRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/47_SolitaireMensRing_3.webp"
 },
 {
  "name": "Mens Wrist Band",
  "price": 8500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 8,
  "category": "Men's Wrist Band",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/48_MensWristBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/48_MensWristBand_1.webp, https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/48_MensWristBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/48_MensWristBand_3.webp"
 },
 {
  "name": "Parallel Mens Band",
  "price": 5000,
  "width": "9.10mm",
  "weight": "8gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/49_ParallelMensBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/49_ParallelMensBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/49_ParallelMensBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/49_ParallelMensBand_3.webp"
 },
 {
  "name": "Asymmetric Solitaire Band",
  "price": 4500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/50_AsymmetricSolitaireBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/50_AsymmetricSolitaireBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/50_AsymmetricSolitaireBand_2.webp"
 },
 {
  "name": "Mens Enamel Diamond Band ",
  "price": 3500,
  "width": "7mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/51_MensEnamelDiamondBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/51_MensEnamelDiamondBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/51_MensEnamelDiamondBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/51_MensEnamelDiamondBand_3.webp"
 },
 {
  "name": "Diamond Chain Unisex Band ",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 7,
  "category": "Men's Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/52_DiamondChainUnisexBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/52_DiamondChainUnisexBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/52_DiamondChainUnisexBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/52_DiamondChainUnisexBand_3.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/52_DiamondChainUnisexBand_4.webp"
 },
 {
  "name": "Baguette Ring",
  "price": 4000,
  "width": "9.10mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/53_BaguetteRing.webp"
 },
 {
  "name": "Multi Overlapped Band",
  "price": 5500,
  "width": "15mm",
  "weight": "8gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/54_MultiOverlappedBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/54_MultiOverlappedBand_1.webp"
 },
 {
  "name": "Diamond band",
  "price": 2850,
  "width": "5mm",
  "weight": "2.5gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/55_Diamondband.webp"
 },
 {
  "name": "Simple Cross Band",
  "price": 2300,
  "width": "6mm",
  "weight": "3.52gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/56_SimpleCrossBand.webp"
 },
 {
  "name": "Pear & Oval Halo Bracelet",
  "price": 7500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "Yellow",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/57_Pear&OvalHaloBracelet.webp"
 },
 {
  "name": "Baguette Bracelet",
  "price": 14500,
  "width": "4inches",
  "weight": "29.50gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/58_BaguetteBracelet.webp"
 },
 {
  "name": "Flora Bracelet",
  "price": 7500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/59_FloraBracelet.webp"
 },
 {
  "name": "Loren Bracelet",
  "price": 7500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/60_LorenBracelet.webp"
 },
 {
  "name": "Jade Flower Bracelet",
  "price": 6500,
  "width": "15.5mm",
  "weight": "10gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/61_JadeFlowerBracelet.webp"
 },
 {
  "name": "Sleek Solitaire Bracelet",
  "price": 5500,
  "width": "6mm",
  "weight": "8gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/62_SleekSolitaireBracelet.webp"
 },
 {
  "name": "Maria Marquise Bracelet",
  "price": 9900,
  "width": "15mm",
  "weight": "17gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/63_MariaMarquiseBracelet.jpeg"
 },
 {
  "name": "Marquise Leaves Bracelet",
  "price": 7500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/64_MarquiseLeavesBracelet.webp"
 },
 {
  "name": "Minimal Baguette Ring",
  "price": 2000,
  "width": "5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/65_MinimalBaguetteRing.webp"
 },
 {
  "name": "Minimal Diamond Ring",
  "price": 2200,
  "width": "3mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/66_MinimalDiamondRing.webp"
 },
 {
  "name": "Halo Baguette Ring",
  "price": 2300,
  "width": "5.5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/67_HaloBaguetteRing.webp"
 },
 {
  "name": "Parallel Baguette Band",
  "price": 3000,
  "width": "5mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/68_ParallelBaguetteBand.webp"
 },
 {
  "name": "Radiant Diamond Band",
  "price": 2850,
  "width": "5mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/69_RadiantDiamondBand.webp"
 },
 {
  "name": "Arley Ring",
  "price": 2200,
  "width": "6mm",
  "weight": "2.3gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/70_ArleyRing.webp"
 },
 {
  "name": "Cilla Ring - 3 Tone",
  "price": 3000,
  "width": "18mm",
  "weight": "4gm",
  "color": "White, Rose, Yellow",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/71_CillaRing-3Tone.webp"
 },
 {
  "name": "Jelica Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/72_JelicaBand.webp"
 },
 {
  "name": "Dia Solitaire Band",
  "price": 3000,
  "width": "9.10mm",
  "weight": "5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/73_DiaSolitaireBand.webp"
 },
 {
  "name": "Kiel Ring ",
  "price": 3000,
  "width": "8mm",
  "weight": "3.5gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/74_kielRing.webp"
 },
 {
  "name": "Double Ring Cocktail Ring ",
  "price": 15500,
  "width": "4inches",
  "weight": "20gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/75_DoubleRingCocktailRing.webp"
 },
 {
  "name": "Solitaire Cocktail Ring",
  "price": 5900,
  "width": "22mm",
  "weight": "8.9gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/76_SolitaireCocktailRing.webp"
 },
 {
  "name": "Solitaire Cross Cocktail Band ",
  "price": 5500,
  "width": "20mm",
  "weight": "6gm",
  "color": "Rose, White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/77_SolitaireCrossCocktailBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/77_SolitaireCrossCocktailBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/77_SolitaireCrossCocktailBand_2.webp"
 },
 {
  "name": "Solitaire Band",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "Yellow",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/78_SolitaireBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/78_SolitaireBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/78_SolitaireBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/78_SolitaireBand_3.webp"
 },
 {
  "name": "Flat Pave Band",
  "price": 4500,
  "width": "6mm",
  "weight": "5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/79_FlatPaveBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/79_FlatPaveBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/79_FlatPaveBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/79_FlatPaveBand_3.webp"
 },
 {
  "name": "Rian Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/80_RianBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/80_RianBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/80_RianBand_2.webp"
 },
 {
  "name": "Via Baguette Ring",
  "price": 3300,
  "width": "13mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/81_ViaBaguetteRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/81_ViaBaguetteRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/81_ViaBaguetteRing_2.webp"
 },
 {
  "name": "Radiant Diamond Eternity Band",
  "price": 2500,
  "width": "5mm",
  "weight": "3.62gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/82_RadiantDiamondEternityBand.webp"
 },
 {
  "name": "Lisa Eternity Band",
  "price": 2300,
  "width": "5mm",
  "weight": "2.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/83_LisaEternityBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/83_LisaEternityBand_1.webp"
 },
 {
  "name": "Via Rose Band",
  "price": 4500,
  "width": "13mm",
  "weight": "5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/84_ViaRoseBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/84_ViaRoseBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/84_ViaRoseBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/84_ViaRoseBand_3.webp"
 },
 {
  "name": "Zen Minimal Ring",
  "price": 1800,
  "width": "5.10mm",
  "weight": "1.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/85_ZenMinimalRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/85_ZenMinimalRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/85_ZenMinimalRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/85_ZenMinimalRing_3.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/85_ZenMinimalRing_4.webp"
 },
 {
  "name": "Tana Cocktail Solitaire Band",
  "price": 4500,
  "width": "10mm",
  "weight": "5.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/86_TanaCocktailSolitaireBand.webp"
 },
 {
  "name": "Rian Solitaire Minimal Ring",
  "price": 2500,
  "width": "6mm",
  "weight": "2.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/87_RianSolitaireMinimalRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/87_RianSolitaireMinimalRing_1.webp"
 },
 {
  "name": "Custom Wifey Ring",
  "price": 2500,
  "width": "11mm",
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/88_CustomWifeyRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/88_CustomWifeyRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/88_CustomWifeyRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/88_CustomWifeyRing_3.webp"
 },
 {
  "name": "Drop Stack Set",
  "price": 5500,
  "width": "20mm",
  "weight": "6.52gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/89_DropStackSet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/89_DropStackSet_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/89_DropStackSet_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/89_DropStackSet_3.webp"
 },
 {
  "name": "Solitaire Stack Set",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/90_SolitaireStackSet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/90_SolitaireStackSet_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/90_SolitaireStackSet_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/90_SolitaireStackSet_3.webp"
 },
 {
  "name": "Pave Band Stack Set",
  "price": 4500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/91_PaveBandStackSet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/91_PaveBandStackSet_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/91_PaveBandStackSet_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/91_PaveBandStackSet_3.webp"
 },
 {
  "name": "Cross Band",
  "price": 3500,
  "width": "25mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/92_CrossBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/92_CrossBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/92_CrossBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/92_CrossBand_3.webp"
 },
 {
  "name": "Random Set Baguette Ring",
  "price": 2500,
  "width": "9.10mm",
  "weight": "3.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/93_RandomSetBaguetteRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/93_RandomSetBaguetteRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/93_RandomSetBaguetteRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/93_RandomSetBaguetteRing_3.webp"
 },
 {
  "name": "Solitaire Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "5.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/94_SolitaireBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/94_SolitaireBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/94_SolitaireBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/94_SolitaireBand_3.webp"
 },
 {
  "name": "Cushion Halo Solitaire Ring",
  "price": 2500,
  "width": "9.10mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/95_CushionHaloSolitaireRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/95_CushionHaloSolitaireRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/95_CushionHaloSolitaireRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/\/95_CushionHaloSolitaireRing_3.webp"
 },
 {
  "name": "Three Row Diamond Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "5.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/96_ThreeRowDiamondBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/96_ThreeRowDiamondBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/96_ThreeRowDiamondBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/96_ThreeRowDiamondBand_3.webp"
 },
 {
  "name": "Baguette Chain Bracelet",
  "price": 2300,
  "width": "15.5mm",
  "weight": "3gm",
  "color": "Rose",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/97_BaguetteChainBracelet.webp"
 },
 {
  "name": "Three In One Studs",
  "price": 2500,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/98_ThreeInOneStuds.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/98_ThreeInOneStuds_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/98_ThreeInOneStuds_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/98_ThreeInOneStuds_3.webp"
 },
 {
  "name": "Two In One Earrings",
  "price": 3000,
  "width": "15mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/99_TwoInOneEarrings.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/99_TwoInOneEarrings_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/99_TwoInOneEarrings_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/99_TwoInOneEarrings_3.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/99_TwoInOneEarrings_4.webp "
 },
 {
  "name": "Evil Eye Bracelet",
  "price": 2000,
  "width": "6mm",
  "weight": "2.5gm",
  "color": "Rose",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/100_EvilEyeBracelet.webp"
 },
 {
  "name": "Evil Eye Enamel Necklace",
  "price": 2500,
  "width": "20mm",
  "weight": "4gm",
  "color": "Yellow",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/101_EvilEyeEnamelNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/101_EvilEyeEnamelNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Emerald Minimal Ring",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/102_EmeraldMinimalRing.webp"
 },
 {
  "name": "Halo Minimal Ring",
  "price": 2000,
  "width": "6mm",
  "weight": "2.5gm",
  "color": "Rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/103_HaloMinimalRing.webp"
 },
 {
  "name": "Three In One Studs",
  "price": 2500,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/104_ThreeInOneStuds.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/104_ThreeInOneStuds_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/104_ThreeInOneStuds_2.webp "
 },
 {
  "name": "Bow Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/105_BowNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Halo Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/106_HaloNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Oval Minimal Necklace ",
  "price": 2000,
  "width": "9mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/107_OvalMinimalNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Leo Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/108_LeoZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Pave Round Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/109_PaveRoundNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Cluster Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/110_ClusterNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Gemini Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/111_GeminiZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Double Halo Necklace",
  "price": 2000,
  "width": "12mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/112_DoubleHaloNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Halo Square Necklace ",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/113_HaloSquareNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Baguette Necklace",
  "price": 2000,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/114_BaguetteNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Cancer Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/115_CancerZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Thunder Watch charm",
  "price": 1300,
  "width": "3mm",
  "weight": "1.5gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/116_ThunderWatchcharm.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/116_ThunderWatchcharm_1.webp"
 },
 {
  "name": "Palm Tree Charm",
  "price": 1300,
  "width": "3mm",
  "weight": "1.5gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/117_PalmTreeCharm.webp"
 },
 {
  "name": "Scissor Charm ",
  "price": 1300,
  "width": "3mm",
  "weight": "1.5gm",
  "color": "White",
  "other": "*This does not include watch with it",
  "categoryNumber": 9,
  "category": "Watch Accessories",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/118_ScissorCharm.webp"
 },
 {
  "name": "Heart Studs",
  "price": 2000,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/119_HeartStuds.webp"
 },
 {
  "name": "Cushion Stack Set",
  "price": 3850,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/120_CushionStackSet.webp"
 },
 {
  "name": "Ruby Via Bracelet",
  "price": 7500,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/121_RubyViaBracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/121_RubyViaBracelet_1.webp"
 },
 {
  "name": "Ciara Hoops ",
  "price": 2500,
  "width": "18mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/122_CiaraHoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/122_CiaraHoops_1.webp"
 },
 {
  "name": "Leaf Earrings",
  "price": 2500,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/123_LeafEarrings.webp"
 },
 {
  "name": "Milla Ring",
  "price": 2300,
  "width": "5mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/124_MillaRing.webp"
 },
 {
  "name": "Emerald Ring",
  "price": 2500,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/125_EmeraldRing.webp"
 },
 {
  "name": "Dreamer Eternity Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/126_DreamerEternityBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/126_DreamerEternityBand_1.webp"
 },
 {
  "name": "Chevron Baguette Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/127_ChevronBaguetteBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/127_ChevronBaguetteBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/127_ChevronBaguetteBand_2.webp"
 },
 {
  "name": "Graca Round Eternity Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/128_GracaRoundEternityBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/128_GracaRoundEternityBand_1.webp"
 },
 {
  "name": "Joana Eternity Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/129_JoanaEternityBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/129_JoanaEternityBand_1.webp"
 },
 {
  "name": "Two Tone Band",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White, Yellow",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/130_TwoToneBand.webp"
 },
 {
  "name": "Double Solitaire Ring",
  "price": 2850,
  "width": "12mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/131_DoubleSolitaireRing.webp"
 },
 {
  "name": "Minimal Hoops ",
  "price": 2300,
  "width": "10mm",
  "weight": "2.5gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/132_MinimalHoops.webp"
 },
 {
  "name": "Halo Studs ",
  "price": 2300,
  "width": "10mm",
  "weight": "3gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/133_HaloStuds.webp"
 },
 {
  "name": "Halo Necklace ",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/134_HaloNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Luck Charm Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/135_LuckCharmNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Diamond Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/136_DiamondNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Heart Studs ",
  "price": 2300,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/137_HeartStuds.webp"
 },
 {
  "name": "Mop Necklace With Letter K",
  "price": 2500,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/138_MopNecklaceWithLetterK.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Dome Pave Necklace",
  "price": 2300,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/139_DomePaveNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Double Halo Heart",
  "price": 2300,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/140_DoubleHaloHeart.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Scorpion Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/141_ScorpionZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Sagittarius Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/142_SagittariusZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Libra Zodiac Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/143_LibraZodiacNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Charm Necklace",
  "price": 3000,
  "width": "9.10mm",
  "weight": "3.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/144_CharmNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Love necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "4gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/145_Lovenecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Evil Eye Necklace",
  "price": 2000,
  "width": "15.5mm",
  "weight": "13gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/146_EvilEyeNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/146_EvilEyeNecklace_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/146_EvilEyeNecklace_2.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Evil Eye Bracelet",
  "price": 2850,
  "width": "15.5mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/147_EvilEyeBracelet.webp"
 },
 {
  "name": "Semi Diamond Earrings",
  "price": 3000,
  "width": "20mm",
  "weight": "4gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/148_SemiDiamondEarrings.webp"
 },
 {
  "name": "Semi Diamond Pendant ",
  "price": 2500,
  "width": "20mm",
  "weight": "3gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/149_SemiDiamondPendant.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Diamond Hoops",
  "price": 3500,
  "width": "30mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/150_DiamondHoops.webp"
 },
 {
  "name": "Halo Studs",
  "price": 2000,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/151_HaloStuds.webp"
 },
 {
  "name": "Evil Eye Enamel Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/152_EvilEyeEnamelNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Evil Eye With Zodiac And Initials Necklace",
  "price": 3000,
  "width": "9.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/153_EvilEyeWithZodiacAndInitialsNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Evil Eye Necklace",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/154_EvilEyeNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Hot Air Balloon Necklace",
  "price": 2500,
  "width": "20mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/155_HotAirBalloonNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Diamond Asymmetric Bali ",
  "price": 2500,
  "width": "18mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/156_DiamondAsymmetricBali.webp"
 },
 {
  "name": "Diamond Hoops ",
  "price": 3500,
  "width": "30mm",
  "weight": "5.8gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/157_DiamondHoops.webp"
 },
 {
  "name": "Bow Studs",
  "price": 2000,
  "width": "10mm",
  "weight": "3.8gm",
  "color": "White",
  "other": "Available in yellow, rose, white\nEarrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/158_BowStuds.webp"
 },
 {
  "name": "Eternity Band Stack ",
  "price": 6000,
  "width": "18mm",
  "weight": "5.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/159_EternityBandStack.webp",
  "tags": "Stack Rings"
 },
 {
  "name": "Cushion Classic Solitaire",
  "price": 2300,
  "width": "9.10mm",
  "weight": "2.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/160_CushionClassicSolitaire.webp"
 },
 {
  "name": "Evil Eye Anklet",
  "price": 1800,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/161_EvilEyeAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/161_EvilEyeAnklet_1.webp",
  "tags": "anklets"
 },
 {
  "name": "Charm Anklet",
  "price": 1500,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/162_CharmAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/162_CharmAnklet_1.webp",
  "tags": "anklets"
 },
 {
  "name": "Evil Eye Anklet",
  "price": 1800,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/163_EvilEyeAnklet.webp",
  "tags": "anklets"
 },
 {
  "name": "Charm Anklet",
  "price": 1350,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/164_CharmAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/164_CharmAnklet_1.webp",
  "tags": "anklets"
 },
 {
  "name": "Pear Charm Anklet",
  "price": 1800,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/165_PearCharmAnklet.webp"
 },
 {
  "name": "Diamond Charm Anklet",
  "price": 1500,
  "width": "12mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/166_DiamondCharmAnklet.webp",
  "tags": "anklets"
 },
 {
  "name": "Halo Mangalsutra Necklace",
  "price": 3500,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/167_HaloMangalsutraNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/167_HaloMangalsutraNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "mangalsutra"
 },
 {
  "name": "Flora Mangalsutra Necklace",
  "price": 3500,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/168_FloraMangalsutraNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/168_FloraMangalsutraNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "mangalsutra"
 },
 {
  "name": "Classic Mangalsutra Necklace",
  "price": 3500,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/169_ClassicMangalsutraNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "tags": "mangalsutra"
 },
 {
  "name": "Marquise Drop Necklace",
  "price": 3500,
  "width": "16.10mm",
  "weight": "4.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/170_MarquiseDropNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/170_MarquiseDropNecklace_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Simple Bar Necklace",
  "price": 2300,
  "width": "12.10mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/171_SimpleBarNecklace.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)"
 },
 {
  "name": "Emerald Oval Band",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/172_EmeraldOvalBand.webp"
 },
 {
  "name": "Emerald Stack Ring",
  "price": 3000,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/173_EmeraldStackRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/173_EmeraldStackRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/173_EmeraldStackRing_2.webp",
  "tags": "stack rings"
 },
 {
  "name": "Trion Ring",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/174_TrionRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/174_TrionRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/174_TrionRing_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/174_TrionRing_3.webp"
 },
 {
  "name": "Trion Ring",
  "price": 2000,
  "width": "9.10mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/175_TrionRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/175_TrionRing_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/175_TrionRing_2.webp"
 },
 {
  "name": "Baguette Stack Set",
  "price": 4950,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/176_BaguetteStackSet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/176_BaguetteStackSet_1.webp",
  "tags": "stack rings"
 },
 {
  "name": "Eternity Audrey Band",
  "price": 3500,
  "width": "9.10mm",
  "weight": "4.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/177_EternityAudreyBand.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/177_EternityAudreyBand_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/177_EternityAudreyBand_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/177_EternityAudreyBand_3.webp"
 },
 {
  "name": "Emerald Band",
  "price": 4500,
  "width": "9.10mm",
  "weight": "5.42gm",
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/178_EmeraldBand.webp"
 },
 {
  "name": "Love Charm Anklet",
  "price": 1800,
  "width": "15.5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/179_LoveCharmAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/179_LoveCharmAnklet_1.webp",
  "tags": "anklets"
 },
 {
  "name": "Minimal Anklet",
  "price": 1200,
  "width": "10mm",
  "weight": "1.5gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/180_MinimalAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/180_MinimalAnklet_1.webp",
  "tags": "anklet"
 },
 {
  "name": "Butterfly Charm Anklet",
  "price": 1800,
  "width": "15.5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/181_ButterflyCharmAnklet.webp",
  "tags": "anklet"
 },
 {
  "name": "Dome Charm Anklet",
  "price": 1800,
  "width": "15.5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/182_DomeCharmAnklet.webp"
 },
 {
  "name": "Luck Charm Anklet",
  "price": 1500,
  "width": "15.5mm",
  "weight": "2gm",
  "color": "White",
  "categoryNumber": 5,
  "category": "Anklet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/183_LuckCharmAnklet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/183_LuckCharmAnklet_1.webp",
  "tags": "anklet"
 },
 {
  "name": "Emerald Oval Solitaire Ring - Christmas Edit ",
  "price": 2000,
  "width": "10mm",
  "weight": "2.8gm",
  "color": "yellow",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/184_EmeraldOvalSolitaireRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Crown Ring - Christmas Edit ",
  "price": 2300,
  "width": "13mm",
  "weight": "3gm",
  "color": "rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/185_CrownRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Baguette Ring - Christmas Edit",
  "price": 1599,
  "width": "7mm",
  "weight": 1.5,
  "color": "rose",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/186_BaguetteRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Flora Ring - Christmas Edit ",
  "price": 1950,
  "width": "10mm",
  "weight": 2.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/187_FloraRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/187_FloraRing-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Flora Set - Christmas Edit ",
  "price": 4950,
  "width": "10mm",
  "weight": 3,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/188_FloraSet-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Pear Ruby Ring - Christmas Edit",
  "price": 1500,
  "width": "12mm",
  "weight": 1.9,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/189_PearRubyRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Pear Solitaire - Christmas Edit",
  "price": 1900,
  "width": "15mm",
  "weight": 2.8,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/190_PearSolitaire-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/190_PearSolitaire-ChristmasEdit_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/190_PearSolitaire-ChristmasEdit_2.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Charm Necklace - Christmas Edit",
  "price": 3500,
  "width": "15mm",
  "weight": 4.2,
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/191_CharmNecklace-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Baguette Studs - Christmas Edit ",
  "price": 2300,
  "weight": 2,
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/192_BaguetteStuds-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/192_BaguetteStuds-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Drop Pear Ring - Christmas Edit ",
  "price": 2500,
  "width": "15mm",
  "weight": 2.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/193_DropPearRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/193_DropPearRing-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Charm Necklace - Christmas Edit",
  "price": 3000,
  "width": "12mm",
  "weight": 3.5,
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/194_CharmNecklace-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/194_CharmNecklace-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Baguette Ring - Christmas Edit",
  "price": 1950,
  "width": "10mm",
  "weight": 2.7,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/195_BaguetteRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/195_BaguetteRing-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Minimal Heart Ring - Christmas Edit",
  "price": 1850,
  "width": "7mm",
  "weight": 1.9,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/196_MinimalHeartRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/196_MinimalHeartRing-ChristmasEdit_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/196_MinimalHeartRing-ChristmasEdit_2.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Oval Solitaire Ring - Christmas Edit",
  "price": 2000,
  "width": "13mm",
  "weight": 2.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/197_OvalSolitaireRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/198_ScatteredMinimalDiamondRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Scattered Minimal Diamond Ring - Christmas Edit",
  "price": 1450,
  "width": "4mm",
  "weight": 1.9,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/198_ScatteredMinimalDiamondRing-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/198_ScatteredMinimalDiamondRing-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Ruby Solitaire Ring - Christmas edit",
  "price": 1950,
  "width": "13mm",
  "weight": 1.9,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/199_RubySolitaireRing-Christmasedit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Minimal Flora Ring - Christmas Edit",
  "price": 1550,
  "width": "12mm",
  "weight": 1.2,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/200_MinimalFloraRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Love Necklace - Christmas Edit",
  "price": 2000,
  "width": "12mm",
  "weight": 2.2,
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/201_LoveNecklace-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/201_LoveNecklace-ChristmasEdit_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/201_LoveNecklace-ChristmasEdit_2.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/201_LoveNecklace-ChristmasEdit_3.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Mini Heart Stack - Christmas Edit",
  "price": 2200,
  "width": "13mm",
  "weight": 2,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/202_MiniHeartStack-ChristmasEdit.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/202_MiniHeartStack-ChristmasEdit_1.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Mini Baguette Stack - Christmas Edit",
  "price": 2050,
  "width": "8mm",
  "weight": 2.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/203_MiniBaguetteStack-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Mini Pear Ring - Christmas Edit",
  "price": 1350,
  "width": "8mm",
  "weight": 1.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/204_MiniPearRing-ChristmasEdit.webp",
  "productCollection": "Christmas Collection",
  "collectionNumber": 3
 },
 {
  "name": "Love Charm Ring ",
  "price": 2500,
  "width": "13mm",
  "weight": 2.4,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/205_LoveCharmRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/205_LoveCharmRing_1.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "rings"
 },
 {
  "name": "Heart Charm Ring",
  "price": 2500,
  "width": "13mm",
  "weight": 2.5,
  "color": "White",
  "categoryNumber": 1,
  "category": "Rings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/206_HeartCharmRing.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/206_HeartCharmRing_1.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "rings"
 },
 {
  "name": "Love Charm Necklace ",
  "price": 3000,
  "width": "20mm",
  "weight": 3,
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/207_LoveCharmNecklace.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "necklace"
 },
 {
  "name": "Love Charm Bracelet",
  "price": 3500,
  "width": "20mm",
  "weight": 3.8,
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/208_LoveCharmBracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/208_LoveCharmBracelet_1.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "bracelet"
 },
 {
  "name": "Infinity Charm Necklace",
  "price": 3500,
  "width": "25mm",
  "weight": 3.8,
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/209_InfinityCharmNecklace.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "necklace"
 },
 {
  "name": "Pave Love Charm Studs",
  "price": 2950,
  "width": "15mm",
  "weight": "4.5gm",
  "color": "White",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/210_PaveLoveCharmStuds.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2,
  "tags": "studs,earrings"
 },
 {
  "name": "Heart Drop Necklace",
  "price": 2500,
  "width": "15mm",
  "weight": "3.5gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/211_HeartDropNecklace.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Heart Drop Bali",
  "price": 2300,
  "width": "12mm",
  "weight": "2.3gm",
  "color": "White",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/212_HeartDropBali.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Heart Hoops",
  "price": 3500,
  "width": "18mm",
  "weight": "4.8gm",
  "color": "white",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/213_HeartHoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/213_HeartHoops_1.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Minimal Diamond Charm Necklace",
  "price": 3000,
  "width": "15mm",
  "weight": "4.5gm",
  "color": "white",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/214_MinimalDiamondCharmNecklace.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Love Charm Studs",
  "price": 3000,
  "width": "15mm",
  "weight": "4.5gm",
  "color": "white",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/215_LoveCharmStuds.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/215_LoveCharmStuds_1.webp",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Heart Charm Necklace",
  "price": 3000,
  "width": "15mm",
  "weight": "3.2gm",
  "color": "white",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/216_HeartCharmNecklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Double Heart Necklace",
  "price": 2300,
  "width": "13mm",
  "weight": "2.9gm",
  "color": "white",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/217_DoubleHeartNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/217_DoubleHeartNecklace_1.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Valentine's Collection",
  "collectionNumber": 2
 },
 {
  "name": "Chand Bracelet",
  "price": 2300,
  "width": "20mm",
  "weight": "2.5gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/218_Chand+Bracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/218_Chand+Bracelet_1.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Initial K Bracelet",
  "price": 2000,
  "width": "15mm",
  "weight": "1.7gm",
  "color": "White",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/219_InitialKBracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/219_InitialKBracelet_1.webp",
  "length": "15inches, 16inches, 18inches and 20inches (model in the picture is wearing 16 inches chain length)",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Initial Necklace",
  "price": 3000,
  "width": "15mm",
  "weight": "1.7gm",
  "color": "White",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/220_InitialNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/220_InitialNecklace_1.webp , https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/220_InitialNecklace_2.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Nazar Bracelet",
  "price": 2000,
  "width": "15mm",
  "weight": "2.8gm",
  "color": "white",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/221_NazarBracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/221_NazarBracelet_1.webp",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Nazar With Inital Bracelet",
  "price": 2300,
  "width": "13mm",
  "weight": "2.5gm",
  "color": "white",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/222_NazarWithInitalBracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/222_NazarWithInitalBracelet_1.webp",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "11 : 11 Studs",
  "price": 2300,
  "width": "13mm",
  "weight": "2.5gm",
  "color": "white",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/223_11-11Studs.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/223_11-11Studs_1.webp",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Minimal Infinity Charm Stud",
  "price": 1900,
  "width": "7mm",
  "weight": "1.5gm",
  "color": "white",
  "other": "Earrings can either be customised in screw, push or flat\nback post.",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/224_MinimalInfinityCharmStud.webp",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Sun And Moon Necklace",
  "price": 2000,
  "width": "9mm",
  "weight": "1.2gm",
  "color": "white",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/225_SunAndMoonNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/225_SunAndMoonNecklace_1.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Palm Tree Charm Necklace",
  "price": 1900,
  "width": "10 mm",
  "weight": "1.5 gm",
  "color": "white",
  "categoryNumber": 3,
  "category": "Necklace",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/226_PalmTreeCharmNecklace.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/226_PalmTreeCharmNecklace_1.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Komal x Drishti Jewels",
  "collectionNumber": 1
 },
 {
  "name": "Double Halo Link Bracelet ",
  "price": 4000,
  "width": "14.20mm",
  "weight": "5.5 gm",
  "color": "yellow ",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/227_Double Halo Link Bracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/227_Double Halo Link Bracelet_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Dainty Charm Link Bracelet",
  "price": 3500,
  "width": "15mm",
  "weight": "4.5gm",
  "color": "rose",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/228_Dainty Charm Link Bracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/228_Dainty Charm Link Bracelet_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Diamond Link Chain Bracelet ",
  "price": 4500,
  "width": "48mm",
  "weight": "5.5gm",
  "color": "yellow",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/229_Diamond Link Chain Bracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/229_Diamond Link Chain Bracelet_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Dainty Charm Link Bracelet",
  "price": 3000,
  "width": "15mm",
  "weight": "4gm",
  "color": "white",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/230_Dainty Charm Link Bracelet.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/230_Dainty Charm Link Bracelet_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Double Infinity Link Bracelet ",
  "price": 3000,
  "width": "20mm",
  "weight": "3gm ",
  "color": "white",
  "categoryNumber": 4,
  "category": "Bracelet",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/231_Double Infinity Link Bracelet.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Baguette Diamond Hoops ",
  "price": 4000,
  "width": "23mm",
  "weight": "5gms",
  "color": "rose",
  "other": "Earrings can either be customised in screw, push or flat",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/232_Baguette Diamond Hoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/232_Baguette Diamond Hoops_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Pear Diamond Hoops ",
  "price": 4000,
  "width": "23mm",
  "weight": "5gm",
  "color": "yellow",
  "other": "Earrings can either be customised in screw, push or flat",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/233_Pear Diamond Hoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/233_Pear Diamond Hoops_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Round Diamond Hoops ",
  "price": 4000,
  "width": "23mm",
  "weight": "4.3gm",
  "color": "white ",
  "other": "Earrings can either be customised in screw, push or flat",
  "categoryNumber": 2,
  "category": "Earrings",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/234_Round Diamond Hoops.webp",
  "sliderImages": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/234_Round Diamond Hoops_1.webp",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4
 },
 {
  "name": "Fancy Cut Mangalsutra Necklace",
  "price": 4000,
  "width": "30mm",
  "weight": "5gm",
  "color": "rose",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/235_Fancy Cut Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 },
 {
  "name": "Flora Drop Mangalsutra Necklace ",
  "price": 4500,
  "width": "15mm",
  "weight": "5.5gm",
  "color": "yellow",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/236_Flora Drop Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 },
 {
  "name": "Oval Charm Mangalsutra Necklace",
  "price": 3000,
  "width": "10mm",
  "weight": "3gm",
  "color": "yellow",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/237_Oval Charm Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 },
 {
  "name": "Diamond Charm Mangalsutra Necklace ",
  "price": 4500,
  "width": "35mm",
  "weight": "5gm",
  "color": "yellow",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/238_Diamond Charm Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 },
 {
  "name": "Heart Charm Mangalsutra Necklace",
  "price": 4000,
  "width": "30mm",
  "weight": "4gm",
  "color": "rose",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/239_Heart Charm Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 },
 {
  "name": "Halo Charm Mangalsutra Necklace",
  "price": 3500,
  "width": "10mm",
  "weight": "3.5gm",
  "color": "white",
  "categoryNumber": 6,
  "category": "Mangalsutra",
  "image": "https:\/\/drijewels-images.s3.ap-south-1.amazonaws.com\/240_Halo Charm Mangalsutra Necklace.webp",
  "length": "Customised According To Size (model in the picture is wearing 6 inches chain length)",
  "productCollection": "Rasksha Bandhan Collection",
  "collectionNumber": 4,
  "tags": "necklace, mangalsutra"
 }
];

 products.map((product) => {
  if (typeof product.sliderImages === "string") {
    product.sliderImages = product.sliderImages.split(",");
  }
  if (typeof product.tags === "string") product.tags = product.tags.split(",");
});

export default products;
